spring:
  application:
    name: UberClone

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: 67f5ef99116@C

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always




