spring:
  application:
    name: UberBackendClone

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
 secretKey: paiosdfqg43j51b4hjbhcafifa87dsf6hk32jhkrj9a7dfhkjhalkasdf97823
